services:
  mysql:
    image: mysql:latest
    container_name: meu_mysql
    restart: always 
    ports:
      - "3308:3307"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d